import type { Camera, Alert, Incident, Guardian, UploadRecord } from './types';

export const cameras: Camera[] = [
  {
    id: 'cam-001',
    name: 'Main Gate',
    location: 'North Entrance, Building A',
    group: 'Campus',
    status: 'online',
    image: 'https://images.pexels.com/photos/258262/pexels-photo-258262.jpeg?auto=compress&cs=tinysrgb&w=800',
    lastUpdate: '2026-09-02 14:32:18',
  },
  {
    id: 'cam-002',
    name: 'Parking Area',
    location: 'Basement Level P2',
    group: 'Office',
    status: 'online',
    image: 'https://images.pexels.com/photos/3731618/pexels-photo-3731618.jpeg?auto=compress&cs=tinysrgb&w=800',
    lastUpdate: '2026-09-02 14:32:15',
  },
  {
    id: 'cam-003',
    name: 'Corridor A',
    location: '2nd Floor, East Wing',
    group: 'Hospital',
    status: 'online',
    image: 'https://images.pexels.com/photos/31377788/pexels-photo-31377788.jpeg?auto=compress&cs=tinysrgb&w=800',
    lastUpdate: '2026-09-02 14:32:10',
  },
  {
    id: 'cam-004',
    name: 'Emergency Exit',
    location: 'Rear, Building C',
    group: 'Factory',
    status: 'maintenance',
    image: 'https://images.pexels.com/photos/2531709/pexels-photo-2531709.jpeg?auto=compress&cs=tinysrgb&w=800',
    lastUpdate: '2026-09-02 14:30:00',
  },
  {
    id: 'cam-005',
    name: 'Reception',
    location: 'Ground Floor, Main Lobby',
    group: 'Office',
    status: 'online',
    image: 'https://images.pexels.com/photos/1170412/pexels-photo-1170412.jpeg?auto=compress&cs=tinysrgb&w=800',
    lastUpdate: '2026-09-02 14:32:20',
  },
  {
    id: 'cam-006',
    name: "Women's Safety Zone",
    location: '3rd Floor, West Wing',
    group: 'Campus',
    status: 'online',
    image: 'https://images.pexels.com/photos/2382969/pexels-photo-2382969.jpeg?auto=compress&cs=tinysrgb&w=800',
    lastUpdate: '2026-09-02 14:32:05',
  },
];

export const alerts: Alert[] = [
  {
    id: 'ALT-2041',
    type: 'Restricted-Zone Intrusion',
    severity: 'critical',
    cameraName: 'Emergency Exit',
    location: 'Rear, Building C',
    timestamp: '2026-09-02 14:28:42',
    confidence: 97,
    description: 'Unidentified person detected entering the restricted emergency exit zone after hours.',
    status: 'new',
    thumbnail: 'https://images.pexels.com/photos/2531709/pexels-photo-2531709.jpeg?auto=compress&cs=tinysrgb&w=400',
  },
  {
    id: 'ALT-2040',
    type: 'Possible Fall',
    severity: 'critical',
    cameraName: 'Corridor A',
    location: '2nd Floor, East Wing',
    timestamp: '2026-09-02 14:15:03',
    confidence: 91,
    description: 'AI detected a person collapsing near the elevator. Potential medical emergency.',
    status: 'escalated',
    thumbnail: 'https://images.pexels.com/photos/31377788/pexels-photo-31377788.jpeg?auto=compress&cs=tinysrgb&w=400',
  },
  {
    id: 'ALT-2039',
    type: 'Crowd Gathering',
    severity: 'warning',
    cameraName: 'Reception',
    location: 'Ground Floor, Main Lobby',
    timestamp: '2026-09-02 13:58:21',
    confidence: 85,
    description: 'Unusual gathering of 12+ individuals detected in the main lobby for over 5 minutes.',
    status: 'acknowledged',
    thumbnail: 'https://images.pexels.com/photos/1170412/pexels-photo-1170412.jpeg?auto=compress&cs=tinysrgb&w=400',
  },
  {
    id: 'ALT-2038',
    type: 'Unattended Object',
    severity: 'warning',
    cameraName: 'Main Gate',
    location: 'North Entrance, Building A',
    timestamp: '2026-09-02 13:42:11',
    confidence: 88,
    description: 'A bag has been left unattended near the main gate entrance for over 10 minutes.',
    status: 'acknowledged',
    thumbnail: 'https://images.pexels.com/photos/258262/pexels-photo-258262.jpeg?auto=compress&cs=tinysrgb&w=400',
  },
  {
    id: 'ALT-2037',
    type: 'Smoke/Fire Warning',
    severity: 'critical',
    cameraName: 'Parking Area',
    location: 'Basement Level P2',
    timestamp: '2026-09-02 13:20:55',
    confidence: 94,
    description: 'Smoke patterns detected near vehicle row 3. Possible fire hazard in the parking basement.',
    status: 'resolved',
    thumbnail: 'https://images.pexels.com/photos/3731618/pexels-photo-3731618.jpeg?auto=compress&cs=tinysrgb&w=400',
  },
  {
    id: 'ALT-2036',
    type: 'Person Detected',
    severity: 'info',
    cameraName: "Women's Safety Zone",
    location: '3rd Floor, West Wing',
    timestamp: '2026-09-02 12:45:30',
    confidence: 79,
    description: 'Person detected loitering outside the women\'s safety zone for an extended period.',
    status: 'resolved',
    thumbnail: 'https://images.pexels.com/photos/2382969/pexels-photo-2382969.jpeg?auto=compress&cs=tinysrgb&w=400',
  },
  {
    id: 'ALT-2035',
    type: 'Camera Tampering',
    severity: 'warning',
    cameraName: 'Emergency Exit',
    location: 'Rear, Building C',
    timestamp: '2026-09-02 11:30:18',
    confidence: 82,
    description: 'Camera angle shift detected. Possible physical tampering or obstruction.',
    status: 'new',
    thumbnail: 'https://images.pexels.com/photos/2531709/pexels-photo-2531709.jpeg?auto=compress&cs=tinysrgb&w=400',
  },
  {
    id: 'ALT-2034',
    type: 'Person Detected',
    severity: 'info',
    cameraName: 'Parking Area',
    location: 'Basement Level P2',
    timestamp: '2026-09-02 10:15:44',
    confidence: 76,
    description: 'Individual detected walking between parked vehicles at unusual hours.',
    status: 'resolved',
    thumbnail: 'https://images.pexels.com/photos/3731618/pexels-photo-3731618.jpeg?auto=compress&cs=tinysrgb&w=400',
  },
  {
    id: 'ALT-2033',
    type: 'Crowd Gathering',
    severity: 'warning',
    cameraName: 'Reception',
    location: 'Ground Floor, Main Lobby',
    timestamp: '2026-09-02 09:22:00',
    confidence: 81,
    description: 'Crowd density exceeding threshold in the reception area during morning hours.',
    status: 'resolved',
    thumbnail: 'https://images.pexels.com/photos/1170412/pexels-photo-1170412.jpeg?auto=compress&cs=tinysrgb&w=400',
  },
];

export const incidents: Incident[] = [
  {
    id: 'INC-0042',
    severity: 'critical',
    cameraName: 'Corridor A',
    location: '2nd Floor, East Wing',
    dateTime: '2026-09-02 14:15:03',
    guardian: 'Daniel Okafor',
    status: 'Open — Escalated',
    type: 'Possible Fall',
    description: 'Elderly visitor collapsed near elevator. Medical response team dispatched.',
    resolution: 'Awaiting medical report. Guardian en route.',
  },
  {
    id: 'INC-0041',
    severity: 'critical',
    cameraName: 'Parking Area',
    location: 'Basement Level P2',
    dateTime: '2026-09-02 13:20:55',
    guardian: 'Sarah Mendez',
    status: 'Resolved',
    type: 'Smoke/Fire Warning',
    description: 'Smoke detected from engine compartment of parked vehicle. Fire services contacted.',
    resolution: 'Fire contained. No injuries. Vehicle owner notified.',
  },
  {
    id: 'INC-0040',
    severity: 'warning',
    cameraName: 'Reception',
    location: 'Ground Floor, Main Lobby',
    dateTime: '2026-09-02 13:58:21',
    guardian: 'James Whitfield',
    status: 'Open — Acknowledged',
    type: 'Crowd Gathering',
    description: 'Protest gathering in main lobby. Security team monitoring situation.',
    resolution: 'Crowd dispersed peacefully. No further action required.',
  },
  {
    id: 'INC-0039',
    severity: 'warning',
    cameraName: 'Main Gate',
    location: 'North Entrance, Building A',
    dateTime: '2026-09-02 13:42:11',
    guardian: 'Aisha Bello',
    status: 'Resolved',
    type: 'Unattended Object',
    description: 'Suspicious bag at main gate. Bomb squad notified as precaution.',
    resolution: 'Bag confirmed as lost luggage. Returned to owner.',
  },
  {
    id: 'INC-0038',
    severity: 'critical',
    cameraName: 'Emergency Exit',
    location: 'Rear, Building C',
    dateTime: '2026-09-02 14:28:42',
    guardian: 'Unassigned',
    status: 'Open — New',
    type: 'Restricted-Zone Intrusion',
    description: 'Unauthorized entry through emergency exit after hours.',
    resolution: 'Investigation in progress. Guard dispatched to location.',
  },
  {
    id: 'INC-0037',
    severity: 'info',
    cameraName: "Women's Safety Zone",
    location: '3rd Floor, West Wing',
    dateTime: '2026-09-02 12:45:30',
    guardian: 'Priya Sharma',
    status: 'Resolved',
    type: 'Person Detected',
    description: 'Individual loitering near restricted zone. Spoken to by security.',
    resolution: 'Person was a waiting visitor. No threat identified.',
  },
];

export const guardians: Guardian[] = [
  {
    id: 'g-001',
    name: 'Daniel Okafor',
    role: 'Head of Security',
    phone: '+1 (555) 102-8841',
    email: 'd.okafor@angel-cctv.com',
    notificationPref: 'Push + SMS + Email',
    status: 'active',
    avatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=200',
  },
  {
    id: 'g-002',
    name: 'Sarah Mendez',
    role: 'Emergency Coordinator',
    phone: '+1 (555) 207-4492',
    email: 's.mendez@angel-cctv.com',
    notificationPref: 'SMS + Email',
    status: 'active',
    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=200',
  },
  {
    id: 'g-003',
    name: 'James Whitfield',
    role: 'Night Patrol Lead',
    phone: '+1 (555) 338-7720',
    email: 'j.whitfield@angel-cctv.com',
    notificationPref: 'Push + SMS',
    status: 'active',
    avatar: 'https://images.pexels.com/photos/1222270/pexels-photo-1222270.jpeg?auto=compress&cs=tinysrgb&w=200',
  },
  {
    id: 'g-004',
    name: 'Aisha Bello',
    role: 'Response Team Member',
    phone: '+1 (555) 419-3305',
    email: 'a.bello@angel-cctv.com',
    notificationPref: 'Push + Email',
    status: 'active',
    avatar: 'https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg?auto=compress&cs=tinysrgb&w=200',
  },
  {
    id: 'g-005',
    name: 'Priya Sharma',
    role: 'Campus Safety Officer',
    phone: '+1 (555) 561-9987',
    email: 'p.sharma@angel-cctv.com',
    notificationPref: 'Email',
    status: 'inactive',
    avatar: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=200',
  },
];

export const uploads: UploadRecord[] = [
  {
    id: 'up-004',
    fileName: 'gate_footage_0902.mp4',
    camera: 'Main Gate',
    location: 'North Entrance, Building A',
    uploadTime: '2026-09-02 14:05:00',
    status: 'analyzed',
    alertsFound: 3,
    fileSize: '42.3 MB',
  },
  {
    id: 'up-003',
    fileName: 'corridor_a_clip_0132.mov',
    camera: 'Corridor A',
    location: '2nd Floor, East Wing',
    uploadTime: '2026-09-02 12:48:00',
    status: 'analyzed',
    alertsFound: 1,
    fileSize: '28.7 MB',
  },
  {
    id: 'up-002',
    fileName: 'parking_basement_0135.avi',
    camera: 'Parking Area',
    location: 'Basement Level P2',
    uploadTime: '2026-09-02 11:20:00',
    status: 'analyzed',
    alertsFound: 2,
    fileSize: '56.1 MB',
  },
  {
    id: 'up-001',
    fileName: 'reception_morning.webm',
    camera: 'Reception',
    location: 'Ground Floor, Main Lobby',
    uploadTime: '2026-09-02 09:00:00',
    status: 'analyzed',
    alertsFound: 1,
    fileSize: '35.4 MB',
  },
];

export const alertTrendData = [
  { label: 'Mon', critical: 1, warning: 4, info: 8 },
  { label: 'Tue', critical: 0, warning: 3, info: 6 },
  { label: 'Wed', critical: 2, warning: 5, info: 10 },
  { label: 'Thu', critical: 1, warning: 2, info: 7 },
  { label: 'Fri', critical: 3, warning: 6, info: 9 },
  { label: 'Sat', critical: 1, warning: 3, info: 4 },
  { label: 'Sun', critical: 0, warning: 2, info: 3 },
];

export const alertTypeData = [
  { label: 'Person Detected', count: 42, severity: 'info' as const },
  { label: 'Restricted-Zone Intrusion', count: 8, severity: 'critical' as const },
  { label: 'Crowd Gathering', count: 15, severity: 'warning' as const },
  { label: 'Possible Fall', count: 6, severity: 'critical' as const },
  { label: 'Smoke/Fire Warning', count: 3, severity: 'critical' as const },
  { label: 'Camera Tampering', count: 5, severity: 'warning' as const },
  { label: 'Unattended Object', count: 11, severity: 'warning' as const },
];

export const cameraUptimeData = [
  { label: 'Main Gate', uptime: 99.8 },
  { label: 'Parking Area', uptime: 98.2 },
  { label: 'Corridor A', uptime: 99.5 },
  { label: 'Emergency Exit', uptime: 87.3 },
  { label: 'Reception', uptime: 99.9 },
  { label: "Women's Safety Zone", uptime: 99.1 },
];

export const topLocationsData = [
  { label: 'Main Lobby', count: 18 },
  { label: 'Parking Basement', count: 14 },
  { label: 'East Wing Corridor', count: 11 },
  { label: 'Main Gate', count: 9 },
  { label: 'Building C Rear', count: 7 },
];

export const responseTimeData = [
  { label: 'Mon', time: 3.2 },
  { label: 'Tue', time: 2.8 },
  { label: 'Wed', time: 4.1 },
  { label: 'Thu', time: 2.5 },
  { label: 'Fri', time: 3.8 },
  { label: 'Sat', time: 2.2 },
  { label: 'Sun', time: 1.9 },
];

export const recentActivity = [
  { id: 'a1', text: 'Alert ALT-2041 escalated to Daniel Okafor', time: '2 min ago', type: 'critical' as const },
  { id: 'a2', text: 'Camera "Emergency Exit" entered maintenance mode', time: '15 min ago', type: 'warning' as const },
  { id: 'a3', text: 'Incident INC-0041 resolved by Sarah Mendez', time: '32 min ago', type: 'secure' as const },
  { id: 'a4', text: 'Upload "gate_footage_0902.mp4" analysis complete', time: '1 hr ago', type: 'info' as const },
  { id: 'a5', text: 'New guardian Priya Sharma added to response team', time: '2 hr ago', type: 'info' as const },
];
